name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests=2.24.0
  - pip=21.3.1
  - mlflow=2.12.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.16.6
      - hydra-joblib-launcher==1.1.2
