name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.3.1
  - pandas=2.2.2
  - scikit-learn=0.24.2
  - matplotlib=3.8.4
  - plotly=5.21.0
  - pillow=10.3.0
  - mlflow=2.12.1
  - pip:
      - wandb==0.16.6
      - omegaconf==2.0.6
